### ISSUE TITLE
Game sometimes crashes when opening a Evil Birthday Present

### ISSUE THREAD

**Issue by jtrent238** [jtrent238/PopularMMOS-EpicProportions-Mod#1]
https://github.com/jtrent238/PopularMMOS-EpicProportions-Mod/blob/61ee56afb8bff732e6af80f85d16fca8b7541ab9/src/main/java/com/jtrent238/epicproportions/blocks/blockBirthdayPresent_Bad.java#L155

`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/10/20 12:46 PM
Description: Ticking memory connection

java.lang.ArithmeticException: / by zero
	at com.jtrent238.epicproportions.blocks.blockBirthdayPresent_Bad.func_149636_a(blockBirthdayPresent_Bad.java:155)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:299)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.jtrent238.epicproportions.blocks.blockBirthdayPresent_Bad.func_149636_a(blockBirthdayPresent_Bad.java:155)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:299)
	at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@59fcd3c2
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 1241169384 bytes (1183 MB) / 1804599296 bytes (1721 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -Xmx4096m -Xms4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	jtcoremod{1.0.0.0} [jtrent238's Core Mod] (DecorativeBlocksMod-1.0.0.2.jar) 
	UCHIJAAAA	decorationmod{1.0.0.2} [§2jtrent238's Decoration Mod] (DecorativeBlocksMod-1.0.0.2.jar) 
	UCHIJAAAA	doritos{1.0.0.0} [jtrent238's Doritos Mod] (doritos-1.0.0.0.jar) 
	UCHIJAAAA	epicproportionsmod{1.5.9.14} [jtrent238's EpicProportions Mod] (epicproportionsmod-1.5.9.14.jar) 
	UCHIJAAAA	epicproportionsmod_christmas{1.0.2.1} [jtrent238's EpicProportions Mod - Christmas Addon] (epicproportionsmod_christmas-1.0.2.1.jar) 
	UCHIJAAAA	epicproportionsmod_halloween{1.0.1.2} [jtrent238's EpicProportions Mod - Halloween Addon] (epicproportionsmod_halloween-1.0.1.2.jar) 
	UCHIJAAAA	hammermod{1.1.3.10} [Hammer Mod] (hammermod-1.1.3.10.jar) 
	UCHIJAAAA	jtrent238bags{1.0.0.1} [jtrent238's Bag Mod] (jtrent238bags-1.0.0.1.jar) 
	UCHIJAAAA	jtrent238drinks{1.0.0.1} [jtrent238's Drinks Mod] (jtrent238drinks-1.0.0.1.jar) 
	UCHIJAAAA	jtrent238flowers{1.0.0.0} [jtrent238's Fancy Flower Mod] (jtrent238flowers-1.0.0.0.jar) 
	UCHIJAAAA	jtrent238sgems{1.0.0.0} [jtrent238's Gems Mod] (jtrent238sgems-1.0.0.0.jar) 
	UCHIJAAAA	jtrent238youtubers{1.0.2.2} [jtrent238's YouTuber Mod] (jtrent238youtubers-1.0.2.2.jar) 
	UCHIJAAAA	lostrecords{1.0.0.0} [jtrent238's Lost Records Mod] (lostrecords-1.0.0.0.jar) 
	UCHIJAAAA	luckyblock{1.0.2.3} [jtrent238's Lucky Block Mod] (luckyblock-1.0.2.3.jar) 
	UCHIJAAAA	obscore{1.4.1} [ObsCore] (obscore-1.4.1_mc1.7.10.jar) 
	UCHIJAAAA	obstrophiesaoa{1.6.0} [ObsTrophies] (obstrophies-1.6.0_mc1.7.10.jar) 
	UCHIJAAAA	moretrophies{1.0.2.6} [jtrent238's More Trophies Mod] (moretrophies-1.0.2.6.jar) 
	UCHIJAAAA	ninjastarmod{1.0.0.0} [jtrent238's NinjaStar Mod] (ninjastarmod-1.0.0.0.jar) 
	UCHIJAAAA	ogpig{1.0.0.0} [OGPig: Birth of the creeper] (ogpig-1.0.0.0.jar) 
	UCHIJAAAA	playerhunter{pre-1.0.0.0} [jtrent238's Player Hunter Mod] (playerhunter-pre-1.0.0.0.jar) 
	UCHIJAAAA	pocketutilities{pre-1.0.0.0} [jtrent238's Pocket Utilities Mod] (pocketutilities-pre-1.0.0.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['jtrent238'/158, l='New World', x=-48.54, y=64.00, z=7.49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by jtrent238** [comment]
Fixed in [1.5.9.15](https://github.com/jtrent238/PopularMMOS-EpicProportions-Mod/releases/tag/1.5.9.15) https://github.com/jtrent238/PopularMMOS-EpicProportions-Mod/commit/823347c165d4d1d6689dd795b266500ad948e690
