### ISSUE TITLE
Mod Crashes on server

### ISSUE THREAD

**Issue by jtrent238** [jtrent238/PopularMMOS-EpicProportions-Mod#3]
https://github.com/jtrent238/PopularMMOS-EpicProportions-Mod/blob/20bd1be2da09311860d9fbea50e349004f9dc680/src/main/java/com/jtrent238/epicproportions/Recipes.java#L117

Game crashes when running mod on server.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 1/18/21 9:47 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.func_77962_s()Z
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.func_77962_s()Z
	at com.jtrent238.epicproportions.Recipes.addShapedRecpies(Recipes.java:117)
	at com.jtrent238.epicproportions.Recipes.registerRecpies(Recipes.java:29)
	at com.jtrent238.epicproportions.EpicProportionsMod.init(EpicProportionsMod.java:704)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1494950128 bytes (1425 MB) / 2351955968 bytes (2243 MB) up to 3787980800 bytes (3612 MB)
	JVM Flags: 0 total; 
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 120 mods loaded, 120 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHI	OpenEye{0.8} [OpenEye] (OpenEye-1.7.10-0.8.jar) 
	UCHI	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHI	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
	UCHI	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCHI	zeldaswordskills{1.7.10-2.5.1} [Zelda Sword Skills] (1.7.10-zeldaswordskills-2.5.1.jar) 
	UCHI	divinerpg{1.4.1.5} [DivineRPG] ([1.7.10][SMP]DivineRPG-1.4.1.5.jar) 
	UCHI	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHI	FloatingRuins{1.7.10.r02} [FloatingRuins] ([1.7.10]FloatingRuins-universal-1.7.10.r02.jar) 
	UCHI	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
	UCHI	antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-1.3.5-1.7.10.jar) 
	UCHI	nevermine{Tslat-1.1.3} [Advent of Ascension] (AoA-Tslat-1.1.3.jar) 
	UCHI	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHI	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHI	BackTools{4.0.0} [BackTools] (BackTools-4.0.0.jar) 
	UCHI	BattleTowers{1.5.1} [Battle Towers] (BattleTowers-1.7.10.jar) 
	UCHI	blockarmor{1.1} [Block Armor] (BlockArmor-1.7.10-1.1.jar) 
	UCHI	chancecubes{1.7.10-2.4.1.0} [Chance Cubes] (ChanceCubes-1.7.10-2.4.1.182.jar) 
	UCHI	TwilightForest{2.3.8dev} [The Twilight Forest] (twilightforest-1.7.10-2.3.8.jar) 
	UCHI	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHI	chococraft{4.1.5} [Clienthax's ChocoCraft] (ChocoCraft-4.1.5.jar) 
	UCHI	coloredchests{0.1.0.9} [Colored Chests] (ColoredChests-1.7.10-0.1.0b9.jar) 
	UCHI	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHI	CustomPets{1.0.5} [Custom Pets] (custompets-1.7.10-1.0.5-universal.jar) 
	UCHI	DeathCounter{4.0.0} [DeathCounter] (DeathCounter-4.0.0.jar) 
	UCHI	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCHI	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCHI	jtcoremod{1.0.0.0} [jtrent238's Core Mod] (DecorativeBlocksMod-1.0.0.2.jar) 
	UCHI	decorationmod{1.0.0.2} [Â§2jtrent238's Decoration Mod] (DecorativeBlocksMod-1.0.0.2.jar) 
	UCHI	dimensionalcake{0.0.1} [Dimensional Cake] (dimensionalcakes-0.0.1.jar) 
	UCHI	doggytalents{1.14.2.317} [Doggy Talents] (DoggyTalents-1.7.10-1.14.2.317-universal.jar) 
	UCHI	dldungeonsjdg{1.11.0.1} [Doomlike Dungeons] (DoomlikeDungeons-1.11.0.1-MC1.7.10.jar) 
	UCHI	doritos{1.0.0.0} [jtrent238's Doritos Mod] (doritos-1.0.0.0.jar) 
	UCHI	duplicatortree{1.0.0.0} [Duplicator Tree] (duplicatortree-1.0.0.0.jar) 
	UCHI	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHI	endercore{1.7.10-0.2.0.39_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.39_beta.jar) 
	UCHE	epicproportionsmod{1.5.9.14} [jtrent238's EpicProportions Mod] (epicproportionsmod-1.5.9.14.jar) 
	UCHI	epicproportionsmod_christmas{1.0.2.1} [jtrent238's EpicProportions Mod - Christmas Addon] (epicproportionsmod_christmas-1.0.2.1.jar) 
	UCHE	epicproportionsmod_halloween{1.0.1.2} [jtrent238's EpicProportions Mod - Halloween Addon] (epicproportionsmod_halloween-1.0.1.2.jar) 
	UCHI	excore{1.5.3} [EXCore] (Excore-1.5.3-1.7.10.jar) 
	UCHI	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCHI	farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar) 
	UCHI	FoodExpansion{1.0} [Food Expansion] (FoodExpansion1.1.1-mc1.7.10.jar) 
	UCHI	FunOres{1.0.3b} [Fun Ores] (FunOres-1.7.10-1.0.3b-12.jar) 
	UCHI	hammermod{1.1.3.10} [Hammer Mod] (hammermod-1.1.3.10.jar) 
	UCHI	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar) 
	UCHI	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHI	headcrumbs{1.7.4} [Headcrumbs] (Headcrumbs-1.7.4.jar) 
	UCHI	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHI	InventoryPets{1.5.2} [Inventory Pets] (inventorypets-1.7.10-1.5.2-universal.jar) 
	UCHI	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHI	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHI	jaffa{1.91.56} [JAFFA (HarvestCraft Addon)] (JAFFA-1.91.56.jar) 
	UCHI	jtrent238drinks{1.0.0.1} [jtrent238's Drinks Mod] (jtrent238drinks-1.0.0.1.jar) 
	UCHI	jtrent238youtubers{1.0.2.2} [jtrent238's YouTuber Mod] (jtrent238youtubers-1.0.2.2.jar) 
	UCHI	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHI	lootbags{2.0.17} [Loot Bags] (LootBags-1.7.10-2.0.17.jar) 
	UCHI	lostrecords{1.0.1.0} [jtrent238's Lost Records Mod] (lostrecords-1.0.1.0.jar) 
	UCHI	luckyblock{1.0.2.3} [jtrent238's Lucky Block Mod] (luckyblock-1.0.2.3.jar) 
	UCHI	lycanitesmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	arcticmobs{1.13.0.5 - MC 1.7.10} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	demonmobs{1.13.0.5 - MC 1.7.10} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	desertmobs{1.13.0.5 - MC 1.7.10} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	forestmobs{1.13.0.5 - MC 1.7.10} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	freshwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	infernomobs{1.13.0.5 - MC 1.7.10} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	junglemobs{1.13.0.5 - MC 1.7.10} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	mountainmobs{1.13.0.5 - MC 1.7.10} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	plainsmobs{1.13.0.5 - MC 1.7.10} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	saltwatermobs{1.13.0.5 - MC 1.7.10} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	shadowmobs{1.13.0.5 - MC 1.7.10} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	swampmobs{1.13.0.5 - MC 1.7.10} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.13.0.5 [1.7.10].jar) 
	UCHI	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
	UCHI	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
	UCHI	Mo' Shiz{1.62.2} [Mo' Shiz] (Mo' Shiz v1.62.2.jar) 
	UCHI	obscore{1.4.1} [ObsCore] (obscore-1.4.1_mc1.7.10.jar) 
	UCHI	obstrophiesaoa{1.6.0} [ObsTrophies] (obstrophies-1.6.0_mc1.7.10.jar) 
	UCHI	moretrophies{1.0.2.6} [jtrent238's More Trophies Mod] (moretrophies-1.0.2.6.jar) 
	UCHI	Morph{0.9.3} [Morph] (Morph-Beta-0.9.3.jar) 
	UCHI	mowziesmobs{1.2.9} [Mowzie's Mobs] (MowziesMobs-1.2.99.jar) 
	UCHI	notenoughpets{2.2.0} [§eNot Enough Pets] (NotEnoughPets-1.7.10-v2.2.0.jar) 
	UCHI	neresources{0.1.0.ManuallyBuilt} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0-128.jar) 
	UCHI	ogpig{1.0.0.0} [OGPig: Birth of the creeper] (ogpig-1.0.0.0.jar) 
	UCHI	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
	UCHI	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHI	OresPlus{0.7.3.41B} [OresPlus] (OresPlus-0.7.3.41B.jar) 
	UCHI	packguard{2.3.0} [PackGuard] (PackGuard-1.7.10-2.3.0d.jar) 
	UCHI	harvestthenether{1.7.10} [Pam's Harvest the Nether] (Pam's Harvest the Nether 1.7.10a.jar) 
	UCHI	simplerecipes{1.7.10a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.7.10a.jar) 
	UCHI	reccomplex{0.9.7.1.1} [Recurrent Complex] (RecurrentComplex-0.9.7.1.1.jar) 
	UCHI	redcow{0.0.1.2} [Red Cow] (RedCow-1.7.10-0.0.1b2-universal.jar) 
	UCHI	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHI	bagableplants{0.0.1.12} [Bagable Plants] (SBM-BagablePlants-1.7.10-0.0.1b12.jar) 
	UCHI	bonetorch{0.0.1.6} [Bone Torch Mod] (SBM-BoneTorch-1.7.10-0.0.1b6.jar) 
	UCHI	cactibucket{0.0.1.20170105151347} [Cacti Bucket] (SBM-CactiBucket-1.7.10-0.0.1b20170105151347-dev-universal.jar) 
	UCHI	cardboardboxes{0.0.1.5} [Cardboard Boxes] (SBM-CardboardBoxes-1.7.10-0.0.1b5-universal.jar) 
	UCHI	vefluids{0.1.1.25} [VoltzEngine Fluids module] (VE-FluidHandling-1.7.10-0.1.1b25.jar) 
	UCHI	sbmgascan{1.0.1.2} [Gas Can] (SBM-GasCan-1.7.10-1.0.1b2-universal.jar) 
	UCHI	smbgrapplinghook{0.1.0.20170514023901} [Grappling Hook] (SBM-GrapplingHook-1.7.10-0.1.0b20170514023901.jar) 
	UCHI	helmbucket{0.0.1.10} [Helm Bucket] (SBM-HelmBucket-1.7.10-0.0.1b10.jar) 
	UCHI	smbmagicmirror{0.0.1.13} [SMB Magic Mirror] (SBM-Magic-Mirror-1.7.10-0.0.1b13-universal.jar) 
	UCHI	sbmoilore{0.1.0.20170512184405} [Oil Ore] (SBM-OilOre-1.7.10-0.1.0b20170512184406.jar) 
	UCHI	woodenshears{0.0.1.4} [Wooden Shears] (SBM-WoodenShears-1.7.10-0.0.1b4-universal.jar) 
	UCHI	SpecialMobs{3.2.2} [Special Mobs] (SpecialMobs-1.7.10-3.2.2.jar) 
	UCHI	thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
	UCHI	erebus{0.4.7} [Erebus] (TheErebus-0.4.7.jar) 
	UCHI	VillageNames{4.1.3} [§6Village Names] (VillageNames-1.7.10-4.1.3.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHI	wailafeatures{0.1.0} [WAILA Features] (WAILA-features-1.7.10-0.1.0.jar) 
	UCHI	WailaHarvestability{1.1.6} [Waila Harvestability] (WailaHarvestability-mc1.7.10-1.1.6.jar) 
	UCHI	wailaplugins{MC1.7.10-0.2.0-25} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.2.0-25.jar) 
	UCHI	waystones{1.0.12} [Waystones] (Waystones-mc1.7.10-1.0.12.jar) 
	UCHI	woodenbucket{0.0.3.9} [Wooden Bucket] (WoodenBucket-1.7.10-0.0.3b9-universal.jar) 
	UCHI	woodenrails{0.0.1.7} [Wooden Rails] (WoodenRails-1.7.10-0.0.1b7.jar) 
	UCHI	zssaddon{1.7.10-alpha-0.0.5-2} [Zelda Sword Skills - Addon] (zeldaswordskillsaddon-v0.0.6.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	PackGuard: MISSING: WTP v1.7.10-1.0.29, MISSING: DamageIndicatorsMod v3.3.2, 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by jtrent238** [comment]
Fixed in [1.5.9.15](https://github.com/jtrent238/PopularMMOS-EpicProportions-Mod/releases/tag/1.5.9.15) https://github.com/jtrent238/PopularMMOS-EpicProportions-Mod/commit/823347c165d4d1d6689dd795b266500ad948e690
